---

- hosts: kubernetes
  remote_user: vagrant
  become: yes
  roles:
    - name: kubernetes/cluster
      tags: update-kubernetes

    - name: kubernetes/cni
      tags: update-kubernetes-cni

    - name: kubernetes/dashboard
      tags: update-kubernetes-dashboard
