---

- name: ZOOKEEPER | Gather OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: ZOOKEEPER | Manage user
  import_tasks: users.yml

- name: ZOOKEEPER | Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zookeeper_user}}"
    group: "{{ zookeeper_group}}"
    mode: 0755
  with_items:
    - "{{ zookeeper_dataDir }}"
    - "{{ zookeeper_logDir }}"

- name: ZOOKEEPER | Manage Debian environment
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: ZOOKEEPER | Manage RedHat environment
  include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: ZOOKEEPER | Deploy MyId file
  copy:
    content: "{{ hostvars[inventory_hostname].myid | default(1) }}"
    dest: "{{ zookeeper_home }}/conf/myid"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: 0644
  notify: Restart zookeeper

- name: ZOOKEEPER | Manage MyId symlink
  file:
    state: link
    src: "{{ zookeeper_home }}/conf/myid"
    dest: "{{ zookeeper_dataDir }}/myid"
    owner: root
    group: root

- name: ZOOKEEPER | Configuration
  template:
    src: "etc/zookeeper/conf/zoo.cfg.j2"
    dest: "{{ zookeeper_home }}/conf/zoo.cfg"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: 0644
  notify: Restart zookeeper
