db:
    image: "mysql:8.0.19"
    environment:
        MYSQL_ROOT_PASSWORD: mysecretpassword
annotationhub:
    environment:
        MYSQL_ROOT_PASSWORD: mysecretpassword
        MYSQL_REMOTE_PASSWORD: 
    image: "bioconductor/annotationhub_docker"
    links:
     - "db"
    ports:
     - "3000:3000"
    volumes:
     - "./AnnotationHubServer3.0:/AnnotationHubServer3.0"
     - "./data:/data"
    command:  "/bin/bash --login /tmp/start.sh"

