drop database if exists annotationhub;
create database annotationhub;
flush privileges;
DROP USER IF EXISTS 'hubuser'@'%';
flush privileges;
CREATE USER 'hubuser'@'%' IDENTIFIED BY 'MYSQL_REMOTE_PASSWORD';
GRANT ALL PRIVILEGES ON annotationhub.* TO 'hubuser'@'%' WITH GRANT OPTION;
flush privileges;
DROP USER IF EXISTS 'ahuser'@'%';
flush privileges;
CREATE USER 'ahuser'@'%' IDENTIFIED BY 'MYSQL_REMOTE_PASSWORD';
GRANT ALL PRIVILEGES ON annotationhub.* TO 'ahuser'@'%' WITH GRANT OPTION;
flush privileges;
