---

###
# ZOOKEEPER
###

# Version
zookeeper_version: 3.4.13

# Sources
zookeeper_tar_mirror: http://mirrors.ukfast.co.uk/sites/ftp.apache.org/zookeeper
zookeeper_tar_url: "{{ zookeeper_tar_mirror }}/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz"

# Port
zookeeper_clientPort: 2181

# Directories
zookeeper_home: /etc/zookeeper
zookeeper_dataDir: /data/zookeeper
zookeeper_logDir: /var/log/zookeeper

# User
zookeeper_group: zookeeper
zookeeper_user: zookeeper

# Hosts
zookeeper_hosts: "{{ groups['zookeeper'] | default('127.0.0.1') }}"
